viper port config
cyberkarma/chatserver pull request #2
Opened 2023-07-16 07:57 UTC by cyberkarma

2023-07-16 15:14 UTC, snaffi requested changes

2023-07-16 15:14 UTC, snaffi commented on src/cmd/runserver/runserver.go
> +		}
Не понятно что происходит. Если не смог считать конфиг надо завершить программу. Так как есть шанс запустить не в неправильной конфигурации

2023-07-16 15:14 UTC, snaffi commented on src/cmd/runserver/runserver.go
>  	Run: func(cmd *cobra.Command, args []string) {
Используй RunE вместо Run чтобы команда могла вернуть ошибку

2023-07-16 15:14 UTC, snaffi commented on src/configs/config.go
> +	Pc ProdConfig `mapstructure:"prod"`
Что за прод конфиг? Конфиг может быть только один 

При деплое на прод передашь нужный файл или переменные окружения и всё

2023-07-16 15:14 UTC, snaffi commented on src/configs/config.go
> +}
Зачем вообще отдельная структура тут?

2023-07-16 15:14 UTC, snaffi commented on src/configs/config.go
> +}
Отсутствуют значения по умолчанию

2023-07-16 16:33 UTC, cyberkarma commented on src/cmd/runserver/runserver.go
> +		}
Просто отладка была, убрал

2023-07-16 16:33 UTC, cyberkarma commented on src/cmd/runserver/runserver.go
>  	Run: func(cmd *cobra.Command, args []string) {
+

2023-07-16 16:33 UTC, cyberkarma commented on src/configs/config.go
> +	Pc ProdConfig `mapstructure:"prod"`
+

2023-07-16 16:34 UTC, cyberkarma commented on src/configs/config.go
> +}
+

2023-07-17 06:07 UTC, cyberkarma commented on src/configs/config.go
> +}
+

2023-07-17 06:16 UTC, snaffi requested changes

2023-07-17 06:16 UTC, snaffi commented on src/cmd/runserver/runserver.go
> +	//"github.com/cyberkarma/chatserver/configs"
Удалить

2023-07-17 06:16 UTC, snaffi commented on src/cmd/runserver/runserver.go
>  		if err != nil {
Если ошибка верни её 

Перед возвратом оберни ошибку добавив описание в какой момент произошла ошибка 

Ошибку надо всегда сразу возвращать. Подумай почему 

https://pkg.go.dev/github.com/pkg/errors#section-readme

2023-07-17 06:16 UTC, snaffi commented on src/cmd/runserver/runserver.go
> +		return nil
Фана ради запусти программу дважды. Ру то есть чтобы одновременно две версии работало. Ты удивишься выводу в логах

2023-07-17 06:16 UTC, snaffi commented on src/configs/config.go
> +var vp *viper.Viper
Почему глобальная переменная ?

2023-07-17 11:48 UTC, cyberkarma commented on src/configs/config.go
> +var vp *viper.Viper
+

2023-07-17 14:55 UTC, snaffi requested changes

2023-07-17 14:55 UTC, snaffi commented on src/configs/config.go
> +	vp.SetDefault("port", "localhost:3001")
У тебя порт является числом а тут строка

2023-07-17 14:55 UTC, snaffi commented on src/cmd/runserver/runserver.go
> +			return err
Надо обернуть добавить сообщение что ошибка чтения конфига

2023-07-17 14:58 UTC, merged